export const lang = {
  AuthenticationFailed: "Authentication failed",
  CategoryNotFound: "Category not found",
  CompanyNotFound: "Company not found",
  EmailMismatch: "Email mismatch",
  InternalServerError: "Internal server error",
  InvalidCategoryData: "Invalid category data",
  InvalidCompanyData: "Invalid company data",
  InvalidParam: "Invalid parameter",
  InvalidQuery: "Invalid query",
  InvalidUserData: "Invalid user data",
  JwtVerificationFailed: "JWT verification failed",
  MongodbClose: "MongoDB close",
  MongodbConnected: "MongoDB connected",
  MongodbDisconnected: "MongoDB disconnected",
  MongodbDisconnecting: "MongoDB disconnecting",
  MongodbError: "MongoDB error",
  MongodbOpen: "MongoDB open",
  MongodbReconnected: "MongoDB reconnected",
  NotFound: "Not found",
  Ok: "Ok",
  SecureServerStarted: "Secure server started",
  ServerError: "Server error",
  ServerStarted: "Server started",
  Unauthorized: "Unauthorized",
  UserAlreadyExists: "User already exists",
  UserNotFound: "User not found"
};
