export const lang = {
  Auth0AuthenticationFailed: "Auth0 authentication failed",
  Auth0CallbackUrl: "Auth0 callback URL",
  Auth0Domain: "Auth0 domain",
  Auth0ReturnUrl: "Auth0 return URL",
  BadRequest: "Bad request",
  CategoryNotFound: "Category not found",
  CompanyNotFound: "Company not found",
  CookieDomain: "Cookie domain",
  CorsOrigin: "CORS origin",
  Environment: "Environment",
  InternalServerError: "Internal server error",
  InvalidCategoryData: "Invalid category data",
  InvalidCompanyData: "Invalid company data",
  InvalidIdParam: "Invalid ID parameter",
  InvalidParam: "Invalid parameter",
  InvalidQuery: "Invalid query",
  InvalidUserData: "Invalid user data",
  JwtVerificationFailed: "JWT verification failed",
  LogLevel: "Log level",
  MethodNotAllowed: "Method not allowed. Https is required",
  MongodbAll: "MongoDB all",
  MongodbClose: "MongoDB close",
  MongodbConnected: "MongoDB connected",
  MongodbConnecting: "MongoDB connecting",
  MongodbDatabaseName: "MongoDB database name",
  MongodbDisconnected: "MongoDB disconnected",
  MongodbDisconnecting: "MongoDB disconnecting",
  MongodbError: "MongoDB error",
  MongodbFullSetup: "MongoDB full setup",
  MongodbOpen: "MongoDB open",
  MongodbReconnectFailed: "MongoDB reconnect failed",
  MongodbReconnected: "MongoDB reconnected",
  NotFound: "Not found",
  OK: "OK",
  Port: "Port",
  SecureServerStarted: "Secure server started",
  ServerError: "Server error",
  ServerInfoLogged: "Server info logged",
  ServerStartedOnPort: "Server started on port",
  Unauthorized: "Unauthorized",
  UserAlreadyExists: "User already exists",
  UserNotFound: "User not found",
  ZeroApiServer: "Zero API server, schema ver",
  in: "in",
  ms: "ms"
} as const;
