export const lang = {
  AlreadyExists: "Already exists",
  AppCacheHit: "App cache hit",
  AppCacheMiss: "App cache miss",
  AsyncError: "Async error",
  Auth0AuthenticationFailed: "Auth0 authentication failed",
  Auth0CallbackUrl: "Auth0 callback URL",
  Auth0Domain: "Auth0 domain",
  Auth0ReturnUrl: "Auth0 return URL",
  AuthenticationFailed: "Authentication failed",
  BadRequest: "Bad request",
  Conflict: "Conflict",
  CookieDomain: "Cookie domain",
  CookieSecure: "Cookie secure",
  CorsOrigin: "CORS origin",
  CreatingMongodbConnection: "Creating MongoDB connection",
  CreatingRedisClient: "Creating Redis client",
  Environment: "Environment",
  FailedToStartServer: "Failed to start server",
  Founder: "Founder",
  FoundingAgreement: "Founding Agreement",
  InternalServerError: "Internal server error",
  InvalidData: "Invalid  data",
  InvalidIdParam: "Invalid ID parameter",
  InvalidQuery: "Invalid query",
  JwtVerificationFailed: "JWT verification failed",
  LogLevel: "Log level",
  MethodNotAllowed: "Method not allowed. Https is required",
  ModelsCacheHit: "Models cache hit",
  ModelsCacheMiss: "Models cache miss",
  MongodbAll: "MongoDB all",
  MongodbClose: "MongoDB close",
  MongodbConnected: "MongoDB connected",
  MongodbConnecting: "MongoDB connecting",
  MongodbConnectionCacheHit: "MongoDB connection cache hit",
  MongodbConnectionCacheMiss: "MongoDB connection cache miss",
  MongodbDatabaseName: "MongoDB database name",
  MongodbDisconnected: "MongoDB disconnected",
  MongodbDisconnecting: "MongoDB disconnecting",
  MongodbError: "MongoDB error",
  MongodbFullSetup: "MongoDB full setup",
  MongodbOpen: "MongoDB open",
  MongodbReconnectFailed: "MongoDB reconnect failed",
  MongodbReconnected: "MongoDB reconnected",
  NotFound: "Not found",
  OK: "OK",
  Port: "Port",
  RedisClientCacheHit: "Redis client cache hit",
  RedisClientCacheMiss: "Redis client cache miss",
  RedisConnected: "Redis connected",
  RedisConnecting: "Redis connecting",
  RedisError: "Redis error",
  SecureServerStarted: "Secure server started",
  ServerError: "Server error",
  ServerInfoLogged: "Server info logged",
  ServerStartedOnPort: "Server started on port",
  SyncError: "Sync error",
  Unauthorized: "Unauthorized",
  ZeroApiServer: "Zero API server, schema ver",
  in: "in",
  ms: "ms"
} as const;
