#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# If package.json or package-lock.json changed
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep -qE 'package(-lock)?.json'; then
  # Install dependencies
  npm install --no-audit
fi
